__author__ = "Milinda Samaraweera"
__copyright__ = "Copyright 2016, Milinda Samaraweera"
__license__ = "BDS"
__version__ = "3.0"
__maintainer__ = "Milinda Samaraweera"
__email__ = "milindaatwork@gmail.com"
__status__ = "Production"
